"""Shared helpers. Frontmatter is a small subset: `key: value` lines where the
value is a JSON value or a bare word. No YAML library is needed or used.

Role bodies may include a line of the form `{{fragment:NAME}}`, replaced by the
text of `fragments/NAME.md`, so a rule that several roles share has one source."""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICIES = ("security-boundaries", "human-approvals", "quality-gates", "model-routing")
ROLE_NAMES = ("implementer", "reviewer", "adversarial-reviewer", "transcriber")
PACK_NAMES = (
    "python-untrusted-input",
    "gha-security-dast",
    "threat-model",
    "rf-emcomm",
    "linux-platform",
    "local-llm-routing",
)
FRAGMENT_NAMES = ("report-header", "never-weaken")

# Suggested model tier -> pinned Claude model id. Pinned, not an alias: an alias
# moves when a new model ships, which changes cost and behavior silently. Bumping
# a pin is a CHANGELOG event. The most capable tier is deliberately absent: no
# role may use it, and a human must record the OK.
TIER_MODEL = {"standard": "claude-sonnet-5-5", "cheap": "claude-haiku-5-5"}

# Abstract capability -> host tool names. Order is the order written out.
CLAUDE_TOOLS = {
    "read": ("Read",),
    "search": ("Grep", "Glob"),
    "edit": ("Edit", "Write"),
    "shell": ("Bash",),
    "skills": ("Skill",),
}
# UNVERIFIED against a Copilot run (none logged yet); see README "What is measured".
COPILOT_TOOLS = {"read": "read", "search": "search", "edit": "edit", "shell": "execute"}
CAPABILITY_ORDER = ("read", "search", "edit", "shell", "skills")

GENERATED_DIRS = (".claude/agents", ".claude/skills", ".github/agents")
GENERATED_MARK = "Generated by scripts/generate.py"

FRAGMENT_RE = re.compile(r"^\{\{fragment:([a-z0-9-]+)\}\}$")


def version(root=ROOT):
    return (Path(root) / "VERSION").read_text(encoding="utf-8").strip()


def parse_frontmatter(text, label="<text>"):
    lines = text.splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{label}: missing frontmatter")
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise ValueError(f"{label}: unterminated frontmatter") from None
    data = {}
    for line in lines[1:end]:
        if ":" not in line:
            raise ValueError(f"{label}: bad frontmatter line")
        key, value = line.split(":", 1)
        key = key.strip()
        if not key:
            raise ValueError(f"{label}: empty frontmatter key")
        if key in data:
            raise ValueError(f"{label}: duplicate {key}")
        value = value.strip()
        try:
            data[key] = json.loads(value)
        except json.JSONDecodeError:
            data[key] = value
    return data, "\n".join(lines[end + 1 :]).strip()


def frontmatter(path):
    return parse_frontmatter(Path(path).read_text(encoding="utf-8"), str(path))


def fragment_text(name, root=ROOT):
    if name not in FRAGMENT_NAMES:
        raise ValueError(f"unknown fragment {name!r}; known: {', '.join(FRAGMENT_NAMES)}")
    return (Path(root) / "fragments" / f"{name}.md").read_text(encoding="utf-8").strip()


def resolve_fragments(body, root=ROOT, label="<text>"):
    """Replace every `{{fragment:NAME}}` line with the fragment's text. One level only."""
    out = []
    for line in body.splitlines():
        m = FRAGMENT_RE.fullmatch(line.strip())
        if m:
            text = fragment_text(m.group(1), root)
            if any(FRAGMENT_RE.fullmatch(inner.strip()) for inner in text.splitlines()):
                raise ValueError(f"{label}: fragment {m.group(1)} may not include another fragment")
            out.append(text)
        elif "{{fragment:" in line:
            raise ValueError(f"{label}: fragment marker must be alone on its line: {line.strip()}")
        else:
            out.append(line)
    return "\n".join(out)


def load_roles(root=ROOT):
    roles = []
    for f in sorted((Path(root) / "roles").glob("*.md")):
        meta, body = frontmatter(f)
        meta = dict(meta)
        meta["source"] = body
        meta["body"] = resolve_fragments(body, root, str(f))
        meta["file"] = f.name
        roles.append(meta)
    return roles


def load_packs(root=ROOT):
    packs = []
    for f in sorted((Path(root) / "packs").glob("*/PACK.md")):
        meta, body = frontmatter(f)
        meta = dict(meta)
        meta["body"] = body
        meta["dir"] = f.parent.name
        packs.append(meta)
    return packs


def policy_text(name, root=ROOT):
    return (Path(root) / "policies" / f"{name}.md").read_text(encoding="utf-8").strip()
